/**
 * @file hash_combiner.h
 * @brief Hash combination utilities library with multiple algorithm support
 * @details Provides efficient hash combination algorithms with good distribution 
 *          properties, supporting FNV-1a, golden ratio, and MurmurHash3 implementations
 * @author Your Name
 * @date 2025-09-29
 * @note Compatible with C++11 and later standards, cross-platform support
 */
#pragma once
#ifndef HASH_COMBINER_H
#define HASH_COMBINER_H
#include <functional>
#include <cstdint>
#include <type_traits>
#include <cstring>

/**
 * @namespace hash_combiner
 * @brief Namespace containing hash combination utilities and algorithms
 * @details Provides a unified interface for combining multiple values into a single hash
 */
namespace hash_combiner {

/**
 * @brief Compute hash value using standard library hash function
 * @tparam T Type of the value to hash
 * @param value Value to compute hash for
 * @return Hash value generated by std::hash
 */
template <typename T>
inline size_t hash_value(const T& value) {
    return std::hash<T>{}(value);
}

/**
 * @struct fnv1a_constants
 * @brief Constants for FNV-1a hash algorithm
 * @details Based on the Fowler-Noll-Vo hash function specification
 * @note https://en.wikipedia.org/wiki/Fowler–Noll–Vo_hash_function
 */
struct fnv1a_constants {
    static constexpr size_t basis_32 = 0x811c9dc5ul;    /**< FNV-1a 32-bit basis */
    static constexpr size_t prime_32 = 0x01000193ul;    /**< FNV-1a 32-bit prime */

#if defined(_MSC_VER)
#pragma warning(push)
#pragma warning(disable:4310)
#endif
    static constexpr size_t basis_64 = (size_t)0xcbf29ce484222325ull;  /**< FNV-1a 64-bit basis */
    static constexpr size_t prime_64 = (size_t)0x100000001b3ull;       /**< FNV-1a 64-bit prime */
#if defined(_MSC_VER)
#pragma warning(pop)
#endif
    
    /** 
     * @brief Basis value based on size_t width
     * @return 32-bit basis if size_t is 32 bits, 64-bit basis otherwise
     */
    static constexpr size_t basis = sizeof(size_t) == sizeof(uint32_t) ? basis_32 : basis_64;
    
    /** 
     * @brief Prime value based on size_t width
     * @return 32-bit prime if size_t is 32 bits, 64-bit prime otherwise
     */
    static constexpr size_t prime = sizeof(size_t) == sizeof(uint32_t) ? prime_32 : prime_64;
};

/**
 * @struct golden_ratio_constants
 * @brief Constants for golden ratio hash algorithm
 * @details Uses golden ratio constant for efficient hash mixing operations
 */
struct golden_ratio_constants {
    static constexpr size_t ratio_32 = 0x9e3779b9ul;    /**< Golden ratio 32-bit constant */

#if defined(_MSC_VER)
#pragma warning(push)
#pragma warning(disable:4310)
#endif
    static constexpr size_t ratio_64 = (size_t)0x9e3779b97f4a7c15ull;  /**< Golden ratio 64-bit constant */
#if defined(_MSC_VER)
#pragma warning(pop)
#endif
    
    /** 
     * @brief Golden ratio value based on size_t width
     * @details Value is the product of the golden ratio (√5-1)/2 and 2^64 (or 2^32)
     * @return 32-bit ratio if size_t is 32 bits, 64-bit otherwise
     */
    static constexpr size_t ratio = sizeof(size_t) == sizeof(uint32_t) ? ratio_32 : ratio_64;
};

/**
 * @struct murmur3_constants
 * @brief Constants for MurmurHash3 algorithm
 * @details Implementation constants for the MurmurHash3 specification
 */
struct murmur3_constants {
    static constexpr size_t default_seed = (size_t)0xc70f6907ull;  /**< Default seed for MurmurHash3 */
};

/**
 * @class fnv1a_hash
 * @brief FNV-1a hash algorithm implementation
 * @details Provides excellent distribution and avalanche properties, 
 *          recommended for most general-purpose use cases
 */
class fnv1a_hash {
public:
    /**
     * @brief Get initial seed value
     * @return Initial hash seed based on FNV-1a basis constant
     */
    static constexpr size_t initial_seed() {
        return fnv1a_constants::basis;
    }

    /**
     * @brief Combine const array into hash seed
     * @tparam T Type of array elements
     * @tparam N Size of the array
     * @param[in,out] seed Hash seed to update
     * @param x Const array to combine into seed
     */
    template<class T, std::size_t N>
    static void combine(size_t& seed, const T(&x)[N])
    {
        combine_bytes(seed, x, sizeof(x));
    }

    /**
     * @brief Combine non-const array into hash seed
     * @tparam T Type of array elements
     * @tparam N Size of the array
     * @param[in,out] seed Hash seed to update
     * @param x Non-const array to combine into seed
     */
    template<class T, std::size_t N>
    static void combine(size_t& seed, T(&x)[N])
    {
        combine_bytes(seed, x, sizeof(x));
    }

    /**
     * @brief Combine single value into hash seed
     * @tparam T Type of the value to combine
     * @param[in,out] seed Hash seed to update
     * @param value Value to combine into seed
     */
    template <typename T>
    static void combine(size_t& seed, const T& value) {
        combine_bytes(seed, &value, sizeof(value));
    }

    /**
     * @brief Combine byte sequence into hash seed
     * @param[in,out] seed Hash seed to update
     * @param data Pointer to byte sequence
     * @param length Number of bytes to process
     */
    static void combine_bytes(size_t& seed, const void* data, size_t length) {
        const unsigned char* bytes = reinterpret_cast<const unsigned char*>(data);
        for (size_t i = 0; i < length; ++i) {
#if 1  // FNV-1a variant (XOR then multiply)
            seed ^= static_cast<size_t>(bytes[i]);
            seed *= fnv1a_constants::prime;
#else  // FNV-1 variant (multiply then XOR)
            seed *= fnv1a_constants::prime;
            seed ^= static_cast<size_t>(bytes[i]);
#endif
        }
    }
};

/**
 * @class golden_ratio_hash
 * @brief Golden ratio hash algorithm implementation
 * @details Simple and fast implementation with good performance characteristics,
 *          suitable for performance-critical scenarios
 */
class golden_ratio_hash {
public:
    /**
     * @brief Get initial seed value
     * @return Initial hash seed (0 for golden ratio algorithm)
     */
    static constexpr size_t initial_seed() {
        return 0;
    }

    /**
     * @brief Combine const array into hash seed
     * @tparam T Type of array elements
     * @tparam N Size of the array
     * @param[in,out] seed Hash seed to update
     * @param x Const array to combine into seed
     */
    template<class T, std::size_t N>
    static void combine(size_t& seed, const T(&x)[N])
    {
        combine_bytes(seed, x, sizeof(x));
    }

    /**
     * @brief Combine non-const array into hash seed
     * @tparam T Type of array elements
     * @tparam N Size of the array
     * @param[in,out] seed Hash seed to update
     * @param x Non-const array to combine into seed
     */
    template<class T, std::size_t N>
    static void combine(size_t& seed, T(&x)[N])
    {
        combine_bytes(seed, x, sizeof(x));
    }

    /**
     * @brief Combine single value into hash seed
     * @tparam T Type of the value to combine
     * @param[in,out] seed Hash seed to update
     * @param value Value to combine into seed
     */
    template <typename T>
    static void combine(size_t& seed, const T& value) {
        seed ^= hash_value(value) + golden_ratio_constants::ratio + (seed << 6) + (seed >> 2);
    }

    /**
     * @brief Combine byte sequence into hash seed
     * @param[in,out] seed Hash seed to update
     * @param data Pointer to byte sequence
     * @param length Number of bytes to process
     */
    static void combine_bytes(size_t& seed, const void* data, size_t length) {
        const unsigned char* bytes = reinterpret_cast<const unsigned char*>(data);
        for (size_t i = 0; i < length; ++i) {
            seed ^= hash_value(bytes[i]) + golden_ratio_constants::ratio + (seed << 6) + (seed >> 2);
        }
    }
};

/**
 * @class murmur3_hash
 * @brief MurmurHash3 algorithm implementation
 * @details Fast non-cryptographic hash function with excellent distribution properties,
 *          implements both 32-bit and 64-bit variants
 */
class murmur3_hash {
private:
    /**
     * @brief Load unaligned bytes from memory
     * @param ptr Pointer to memory location
     * @return Loaded value as size_t
     */
    static size_t unaligned_load(const char* ptr) {
        size_t result;
        memcpy(&result, ptr, sizeof(result));
        return result;
    }

    /**
     * @brief Load bytes from memory in little-endian order
     * @param ptr Pointer to memory location
     * @param count Number of bytes to load (1-8)
     * @return Loaded value as size_t
     */
    static size_t load_bytes(const char* ptr, int count) {
        size_t result = 0;
        --count;
        do {
            result = (result << 8) + static_cast<unsigned char>(ptr[count]);
        } while (--count >= 0);
        return result;
    }

    /**
     * @brief Shift mix operation for MurmurHash3
     * @param value Value to mix
     * @return Mixed value
     */
    static size_t shift_mix(size_t value) {
#if defined(_MSC_VER)
#pragma warning(push)
#pragma warning(disable:4293)
#endif
        return value ^ (value >> 47);
#if defined(_MSC_VER)
#pragma warning(pop)
#endif
    }

    /**
     * @brief 32-bit MurmurHash3 implementation
     * @param data Pointer to input data
     * @param length Length of data in bytes
     * @param seed Initial seed value
     * @return 32-bit hash value
     */
    static size_t hash_32(const void* data, size_t length, size_t seed) {
        const size_t multiplier = 0x5bd1e995;
        size_t hash = seed ^ length;
        const char* buffer = static_cast<const char*>(data);

        while (length >= 4) {
            size_t chunk = unaligned_load(buffer);
            chunk *= multiplier;
            chunk ^= chunk >> 24;
            chunk *= multiplier;
            hash *= multiplier;
            hash ^= chunk;
            buffer += 4;
            length -= 4;
        }

        size_t remainder = 0;
        switch (length) {
        case 3:
            remainder = static_cast<unsigned char>(buffer[2]);
            hash ^= remainder << 16;
        case 2:
            remainder = static_cast<unsigned char>(buffer[1]);
            hash ^= remainder << 8;
        case 1:
            remainder = static_cast<unsigned char>(buffer[0]);
            hash ^= remainder;
            hash *= multiplier;
        };

        hash ^= hash >> 13;
        hash *= multiplier;
        hash ^= hash >> 15;
        return hash;
    }

    /**
     * @brief 64-bit MurmurHash3 implementation
     * @param data Pointer to input data
     * @param length Length of data in bytes
     * @param seed Initial seed value
     * @return 64-bit hash value
     */
    static size_t hash_64(const void* data, size_t length, size_t seed) {
#if defined(_MSC_VER)
#pragma warning(push)
#pragma warning(disable:4293)
#endif
        static const size_t multiplier = (((size_t)0xc6a4a793UL) << 32UL) + (size_t)0x5bd1e995UL;
#if defined(_MSC_VER)
#pragma warning(pop)
#endif
        const char* const buffer = static_cast<const char*>(data);
        const size_t aligned_length = length & ~(size_t)0x7;
        const char* const end = buffer + aligned_length;
        
        size_t hash = seed ^ (length * multiplier);
        for (const char* ptr = buffer; ptr != end; ptr += 8) {
            const size_t chunk = shift_mix(unaligned_load(ptr) * multiplier) * multiplier;
            hash ^= chunk;
            hash *= multiplier;
        }

        if ((length & 0x7) != 0) {
            const size_t chunk = load_bytes(end, length & 0x7);
            hash ^= chunk;
            hash *= multiplier;
        }

        hash = shift_mix(hash) * multiplier;
        hash = shift_mix(hash);
        return hash;
    }

public:
    /**
     * @brief Get initial seed value
     * @return Initial hash seed for MurmurHash3 algorithm
     */
    static constexpr size_t initial_seed() {
        return murmur3_constants::default_seed;
    }

    /**
     * @brief Combine const array into hash seed
     * @tparam T Type of array elements
     * @tparam N Size of the array
     * @param[in,out] seed Hash seed to update
     * @param x Const array to combine into seed
     */
    template<class T, std::size_t N>
    static void combine(size_t& seed, const T(&x)[N])
    {
        combine_bytes(seed, x, sizeof(x));
    }

    /**
     * @brief Combine non-const array into hash seed
     * @tparam T Type of array elements
     * @tparam N Size of the array
     * @param[in,out] seed Hash seed to update
     * @param x Non-const array to combine into seed
     */
    template<class T, std::size_t N>
    static void combine(size_t& seed, T(&x)[N])
    {
        combine_bytes(seed, x, sizeof(x));
    }

    /**
     * @brief Combine single value into hash seed
     * @tparam T Type of the value to combine
     * @param[in,out] seed Hash seed to update
     * @param value Value to combine into seed
     */
    template <typename T>
    static void combine(size_t& seed, const T& value) {
        combine_bytes(seed, &value, sizeof(value));
    }

    /**
     * @brief Combine byte sequence into hash seed
     * @param[in,out] seed Hash seed to update
     * @param data Pointer to byte sequence
     * @param length Number of bytes to process
     */
    static void combine_bytes(size_t& seed, const void* data, size_t length) {
        seed = sizeof(size_t) == sizeof(uint32_t) ? hash_32(data, length, seed) : hash_64(data, length, seed);
    }
};

/**
 * @brief Recursive termination function for hash combination
 * @tparam Algorithm Hash algorithm type
 * @param[in,out] seed Hash seed (not used in termination)
 */
template <typename Algorithm>
inline void combine_impl(size_t& /*seed*/) {}

/**
 * @brief Recursive hash combination implementation
 * @tparam Algorithm Hash algorithm type
 * @tparam T Type of the first value
 * @tparam Args Types of remaining values
 * @param[in,out] seed Hash seed to update
 * @param value First value to combine
 * @param args Remaining values to combine
 */
template <typename Algorithm, typename T, typename... Args>
inline void combine_impl(size_t& seed, const T& value, Args... args) {
    Algorithm::combine(seed, value);
    combine_impl<Algorithm>(seed, args...);
}

/**
 * @brief Create combined hash from multiple values
 * @tparam Algorithm Hash algorithm type
 * @tparam Args Types of values to hash
 * @param args Values to compute hash for
 * @return Combined hash value
 */
template <typename Algorithm, typename... Args>
inline size_t make_hash(const Args&... args) {
    size_t seed = Algorithm::initial_seed();
    combine_impl<Algorithm>(seed, args...);
    return seed;
}

/**
 * @brief Combine multiple values into existing hash seed
 * @tparam Algorithm Hash algorithm type
 * @tparam Args Types of values to combine
 * @param[in,out] seed Existing hash seed
 * @param args Values to combine into seed
 */
template <typename Algorithm, typename... Args>
inline void combine_hash(size_t& seed, const Args&... args) {
    combine_impl<Algorithm>(seed, args...);
}

/**
 * @brief Combine byte sequence into existing hash seed
 * @tparam Algorithm Hash algorithm type
 * @param[in,out] seed Existing hash seed
 * @param data Pointer to byte sequence
 * @param length Number of bytes to process
 */
template <typename Algorithm>
inline void combine_hash_bytes(size_t& seed, const void* data, size_t length) {
    Algorithm::combine_bytes(seed, data, length);
}

} // namespace hash_combiner

/**
 * @brief Create combined hash using default algorithm (MurmurHash3)
 * @tparam Args Types of values to hash
 * @param args Values to compute hash for
 * @return Combined hash value
 */
template <typename... Args>
inline size_t make_hash(const Args&... args) {
    return hash_combiner::make_hash<hash_combiner::murmur3_hash>(args...);
}

/**
 * @brief Combine values into existing hash using default algorithm (MurmurHash3)
 * @tparam Args Types of values to combine
 * @param[in,out] seed Existing hash seed
 * @param args Values to combine into seed
 */
template <typename... Args>
inline void combine_hash(size_t& seed, const Args&... args) {
    hash_combiner::combine_hash<hash_combiner::murmur3_hash>(seed, args...);
}

/**
 * @brief Combine byte sequence using default algorithm (MurmurHash3)
 * @param[in,out] seed Existing hash seed
 * @param data Pointer to byte sequence
 * @param length Number of bytes to process
 */
inline void combine_hash_bytes(size_t& seed, const void* data, size_t length) {
    hash_combiner::combine_hash_bytes<hash_combiner::murmur3_hash>(seed, data, length);
}

#endif // HASH_COMBINER_H